name: hall
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  intl: ">=0.16.1 <=0.17.0"  
  google_fonts: ">=1.1.1 <= 1.2.0"
  cupertino_icons: ^1.0.2
  bloc: ">=6.1.1 <=6.2.0" 
  rxdart: ">=0.25.0 <=0.26.0"
  eva_icons_flutter: ">=2.0.1 <=2.1.0" 
  carousel_slider: ">=2.3.1 <=2.4.0" 
  http: ">=0.12.2 <=0.13.0"
  bottom_navy_bar: ">=5.6.0 <=6.0.0"
  flutter_vector_icons: ">=0.2.1 <=0.3.0"
  flutter_staggered_animations: ">=0.1.2 <=0.2.0"
  flutter_rating_bar: ">=3.2.0+1 <=3.3.0"
  page_indicator: ">=0.3.0 <=0.4.0"
  sleek_circular_slider: ">=1.2.0+web <=1.3.0"
  youtube_player_flutter: ">=7.0.0+7 <=7.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  
